1. Create a 3d array with two 2d array

In [27]:
import numpy as np
arr = np.array([[[0,2,4],[6,8,10]],[[1,3,5],[7,9,0]]])
print(arr[0,1])

[ 6  8 10]


2. Stack two 3d array

In [32]:
import numpy as np
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
b = np.stack((arr,a),axis=0)
print("Array is",b.ndim,"dimensional")
print(b)

Array is 4 dimensional
[[[[ 0  2  4]
   [ 6  8 10]]

  [[ 1  3  5]
   [ 7  9  0]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]
12


3. sum of array along side of axis

In [57]:
import numpy as np

array_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Sum along axis 0 (column-wise)
sum_axis_0 = np.sum(array_2d, axis=0)

# Sum along axis 1 (row-wise)
sum_axis_1 = np.sum(array_2d, axis=1)
print(sum_axis_0,sum_axis_1)

[[1 2 3]] [[4 5 6]] [[7 8 9]]
[12 15 18] [ 6 15 24]


In [58]:
import numpy as np

data = np.array([1, 2, 3, 4, 5])

# Variance
variance = np.var(data)

# Standard Deviation
std_dev = np.std(data)

print("Variance:", variance)
print("Standard Deviation:", std_dev)


Variance: 2.0
Standard Deviation: 1.4142135623730951
