1. Create a 3d array with two 2d array

In [27]:
import numpy as np
arr = np.array([[[0,2,4],[6,8,10]],[[1,3,5],[7,9,0]]])
print(arr[0,1])

[ 6  8 10]


2. Stack two 3d array

In [25]:
import numpy as np
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
b = np.stack((arr,a),axis=0)
print("Array is",b.ndim,"dimensional")
print(b)

Array is 4 dimension
[[[[ 0  2  4]
   [ 6  8 10]]

  [[ 1  3  5]
   [ 7  9  0]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]
