### Importing library

In [1]:
import numpy as np

#### Creating a Numpy Array
```np.array()```function is used to convert,create a python list into a array, we can pass any list,tupple or array-like object to create a ndarray.

In [2]:
list = [1,2,3,4]
arr = np.array(list)
print(arr)
type(arr)

[1 2 3 4]


numpy.ndarray

#### Numpy Array  Attributes
1. np.shape: defines the shape of the array (example:3*3)
2. np.ndim: defines the dimensions of the array (example: 2D)
3. np.size: defines the size of the array (example: 9)
4. ndarray.dtype: defines the data type of the elements in the array (example: 'int32') 

In [1]:
list = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype='int32')
shape = np.shape(list)
dimension = np.ndim(list)
size = np.size(list)
print("shape  = ", shape, "dimension =", dimension,"size =", size, list.dtype)

NameError: name 'np' is not defined

#### 2 Dimensions Array
here ```ndarray.reshape()``` function is used it defines the dimension of the array. a two dimension array can be created using ```np.vstack()``` function it simply stack two array _Vertically_ , similarly if you want to stack or append a array in one dimension ```np.hstack()```function is used to stack two array _Horizontally_

In [3]:
arr1 = np.array([1,2,3],dtype='int64')
arr2 = np.array([4,5,6],dtype='int64')
arr3 = np.append(arr1,arr2).reshape(2,3)
# 2 Dimension array by using vstack function
hstack = np.hstack(arr3)  #horizontal stack
vstack = np.vstack(arr3)  #vertical stack
print("arr3= ","\n",arr3 ,"\n","hstack=",hstack,"\n","vstack=","\n",vstack,"\n")

arr3=  
 [[1 2 3]
 [4 5 6]] 
 hstack= [1 2 3 4 5 6] 
 vstack= 
 [[1 2 3]
 [4 5 6]] 



#### 3 Dimensions Array

In [5]:
ndarray = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
print(ndarray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Spliting An Numpy Array 
here in this example below ```np.arange()``` function is used to generate a range of number between two defined numbers 
to split the numpy array ```np.array_split()``` function is used it is used for uneven spliting of array.
<br>for even splits ```np.split()```function is used. it takes 3 parameters:<br> - ndarray : array to be divided.
<br>- indices or section : it represents the index from array is going to split. <br>- axis : it represents the axis of split it is optional parameter.

In [2]:
array = np.arange(0,15)
arr1 = np.array_split(array,[2,6])
print(arr1)

NameError: name 'np' is not defined

#### Slicing and indexing
- Slicing creates a view for numpy array instead of copy it takes 3 parameter ```start:stop:step```
-  Index is 0-based, and accepts negative indices for indexing from the end of the array.

In [18]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[1:9:2])
print(a[4])

[2 4 6 8]
5
