### Importing library

In [1]:
import numpy as np

#### Creating a Numpy Array

In [2]:
list = [1,2,3,4]
arr = np.array(list)
print(arr)

[1 2 3 4]


#### Numpy Array  Attributes
1. np.shape: defines the shape of the array (example:3*3)
2. np.ndim: defines the dimensions of the array (example: 2D)
3. np.size: defines the size of the array (example: 9)
4. ndarray.dtype: defines the data type of the elements in the array (example: 'int32') 

In [3]:
list = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype='int32')
shape = np.shape(list)
dimension = np.ndim(list)
size = np.size(list)
print("shape  = ", shape, "dimension =", dimension,"size =", size, list.dtype)

shape  =  (3, 3) dimension = 2 size = 9 int32


#### 2 Dimensions Array

In [4]:
arr1 = np.array([1,2,3],dtype='int64')
arr2 = np.array([4,5,6],dtype='int64')
arr3 = np.append(arr1,arr2).reshape(2,3)
hstack = np.hstack(arr3)
vstack = np.vstack(arr3)
print("arr3= ","\n",arr3 ,"\n","hstack=",hstack,"\n","vstack=","\n",vstack,"\n")

arr3=  
 [[1 2 3]
 [4 5 6]] 
 hstack= [1 2 3 4 5 6] 
 vstack= 
 [[1 2 3]
 [4 5 6]] 



#### 3 Dimensions Array

In [5]:
ndarray = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
print(ndarray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
